
name: fn build

on:
  push:
    branches:
      - main
      - master
      - release/*

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fn: [fn-keepalive, event-create-thumb]

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
         repository: maxjahn/repo
         path: functions/${{matrix.fn}}
         push: false
